#OOP #ООП #Python #магический_метод 


Важным моментом при написании контекстных менеджеров является обработка исключений, которые возбуждаются внутри блока `with`. Для обработки исключений при использовании контекстных менеджеров на основе классов, мы использовали метод `__exit__()`, который возвращает логический флаг (тип `bool`), указывающий на то, следует ли подавить возбужденное исключение

Для обработки исключений в контекстных менеджерах на основе функций мы должны использовать конструкцию `try-except-finally`

Контекстный менеджер `CustomContextManager`, который просто выводит текст в методах `__enter__()` и `__exit__()` и обрабатывает исключения типа `IndexError`:
```python
class CustomContextManager:
    def __enter__(self):
        print('Вход в контекстный менеджер...')
        return 'Python generation!'

    def __exit__(self, exc_type, exc_value, traceback):
        print('Выход из контекстного менеджера...')
        if isinstance(exc_value, IndexError):
            print(f'Тип возникшего исключения: {exc_type}')
            print(f'Текст исключения: {exc_value}')
            return True                                 # подавляем возбужденное исключение IndexError
        return False
```
с использованием декоратора `@contextmanager` можно переписать в виде:
```python
from contextlib import contextmanager

@contextmanager
def custom_context_manager():
    print('Вход в контекстный менеджер...')
    try:
        yield 'Python generation!'
    except IndexError as error:
        print(f'Тип возбужденного исключения: {type(error)}')
        print(f'Текст исключения: {error}')
    except:
        raise           # если исключение не планируется подавлять, оно должно быть возбуждено повторно
    finally:
        print('Выход из контекстного менеджера...')
```
Вызовем контекстный менеджер:
```python
with custom_context_manager() as manager:
    print(manager)
    print(manager[100])                                 # обращаемся по несуществующему индексу
```
```
Вход в контекстный менеджер...
Python generation!
Тип возбужденного исключения: <class 'IndexError'>
Текст исключения: string index out of range
Выход из контекстного менеджера...
```
Как мы видим, для обработки определенного типа исключения внутри блока `with` нужно добавить соответствующий блок `except <тип исключения>`, в котором нужным образом обработать возбужденное исключение, что соответствует инструкции `return True` метода `__exit__()`. В случае если возникшее исключение не требуется обрабатывать, оно должно быть возбуждено заново с помощью оператора `raise`, что соответствует инструкции `return False` метода `__exit__()`