#python #исключения #ошибки #assert

![[Pasted image 20240607003334.png]]
Оператор `assert` позволяет нам писать проверки работоспособности кода в конкретных местах кода. Эти проверки обычно называют ***утверждениями***. Мы используем такие утверждения для того чтобы убедиться, остаются ли верными определенные условия во время разработки программы.

Если какое-либо из утверждений - это удобный инструмент для документирования, отладки и тестирования кода во время разработки. После того как мы отладили и протестировали наш код с помощью утверждений, мы можем их отключить.

Утверждения могут сделать код более эффективным, устойчивым, и надежным.

Оператор `assert` - это встроенный оператор используемый для проверки того, является ли заданное утверждение истинным или ложным. Если утверждение истинно, то ничего не происходит и выполняется следующая строка кода. Если же утверждение ложно, оператор `assert` останавливает выполнение программы и подобно оператору `raise` возбуждает исключение `AssertionError`.

Синтаксис использования оператора `assert` следующий:
```python
assert <утверждение>
 ```
Также можно добавить дополнительное сообщение, которое описывает подробности возникновения исключительной ситуации. В таком случае синтаксис оператора `assert` будет следующий: ```
```python
assert <утверждение>, <сообщение>
```
При этом такой код примерно эквивалентен этому коду:
```python
if not <утверждение>:
    raise AssertionError(<сообщение>)
```

Оператор `assert` — это средство отладки, а не механизм обработки ошибок времени выполнения программы (исключений). Цель использования оператора `assert` состоит в том, чтобы позволить разра­ботчикам как можно скорее найти вероятную первопричину ошибки. Если в программе ошибки нет, то исключение `AssertionError` никогда не должно возникнуть. В связи с этим не следует писать код, который явно обрабатывает исключения `AssertionError` с помощью конструкции `try-except`.

Инструкция `assert` предназначена для того чтобы сооб­щать разработчикам о неустранённых ошибках в программе. Инструкция `assert` не предназначена для того чтобы сигнализировать об ожидаемых ошибочных условиях, таких как ошибка «Файл не найден», где пользователь может предпринять корректирующие действия или просто попро­бовать еще раз.

Сформулируем основные тезисы относительно оператора `assert`:
- оператор `assert` — это средство отладки, которое проверяет утверждение, выступающее в качестве внутренней самопроверки вашей программы
- оператор `assert` должен применяться только для того чтобы по­могать разработчикам идентифицировать ошибки. Он не является механизмом обработки ошибок времени выполнения программы (исключений)
- оператор `assert` может быть глобально отключен в настройках интерпретатора
#### Примеры использования оператор `assert`
##### Пример 1
```python
age = 29                # возраст человека
assert age > 0, 'Возраст должен быть положительным числом'
```
Код использует оператор `assert` для проверки того, является ли возраст положительным числом. В данном случае утверждение `age > 0` истинно, поэтому оператор `assert` ничего не делает. Если бы переменная `age` имела отрицательное значение, то оператором `assert` было бы возбуждено исключение `AssertionError`.
##### Пример 2
При выполнении операции деления следует учитывать, что на ноль делить нельзя. Если делитель окажется равным нулю, будет возбуждено исключение `ZeroDivisionError`
```python
num1 = 20
num2 = 0

assert num2 != 0, 'Делитель равен нулю.'

print('Частное равно:', num1 / num2)
```
Этот код использует оператор `assert` для проверки того, не равен ли нулю делитель. В данном случае утверждение `num2 != 0` ложно поэтому оператором `assert` будет возбужденно исключение `AssertionError` вместе с добавленным нами сообщением.

Если изменить значение переменной `num2` на `10` и выполнить нашу программу снова, то на этот раз утверждение `num2 != 0` окажется истинным и исключение возбуждено не будет. Таким образом, на экране выведется результат деления:
```
Частное равно: 2.0
```